repos:  
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0  # Use the ref you want to point at
      hooks:
      -   id: no-commit-to-branch
          args: [--branch, master]
      -   id: check-added-large-files
          args: ['--maxkb=500']

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.4
    hooks:
      # Run the linter.
      - id: ruff
      # Run the formatter.
      - id: ruff-format
